// <auto-generated />
using System;
using FoodicsOrdersScrapperService.infrastructure.persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodicsOrdersScrapperService.Migrations
{
    [DbContext(typeof(FoodicsDbContext))]
    partial class FoodicsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodicsOrdersScrapperService.domain.entities.Order", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("app_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("check_number")
                        .HasColumnType("int");

                    b.Property<string>("customer_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("delay_in_seconds")
                        .HasColumnType("int");

                    b.Property<int?>("delivery_status")
                        .HasColumnType("int");

                    b.Property<double>("discount_amount")
                        .HasColumnType("float");

                    b.Property<int?>("discount_type")
                        .HasColumnType("int");

                    b.Property<int>("guests")
                        .HasColumnType("int");

                    b.Property<string>("kitchen_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("number")
                        .HasColumnType("int");

                    b.Property<string>("promotion_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reference")
                        .HasColumnType("int");

                    b.Property<string>("reference_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rounding_amount")
                        .HasColumnType("float");

                    b.Property<int>("source")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<double>("subtotal_price")
                        .HasColumnType("float");

                    b.Property<double>("tax_exclusive_discount_amount")
                        .HasColumnType("float");

                    b.Property<double>("total_price")
                        .HasColumnType("float");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
